"""add estimated_cost_usd to agent_runs

Revision ID: 33c02cae4e0e
Revises: 816debd48a11
Create Date: 2026-08-14 17:09:26.595782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c02cae4e0e'
down_revision: Union[str, None] = '816debd48a11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('estimated_cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'estimated_cost_usd')
    # ### end Alembic commands ###
